workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 90
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: comemgic_admin

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: net.planora.app
      vars:
        NODE_VERSION: 18
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "net.planora.app"
      xcode: 26.1

    scripts:
      - name: Set up Node and install dependencies
        script: |
          nvm install $NODE_VERSION || echo "nvm already installed"
          nvm use $NODE_VERSION || echo "using default node"
          npm install --legacy-peer-deps

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor platforms
        script: npm run cap:sync

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Set up code signing
        script: |
          echo "=== Initializing keychain ==="
          keychain initialize
          
          echo "=== Fetching profiles from Apple ==="
          # שים לב: בלי --install ובלי שם הפרופיל כארגומנט חופשי
          app-store-connect fetch-signing-files --bundle-id "net.planora.app" --type IOS_APP_STORE
          
          echo "=== Adding certificates to keychain ==="
          keychain add-certificates
          
          echo "=== Applying profiles to Xcode project ==="
          # שים לב: בלי --bundle-id
          xcode-project use-profiles

      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" 2>/dev/null || echo "0")
          agvtool new-version -all $((LATEST_BUILD + 1))

      - name: Clean build folder
        script: |
          cd ios/App
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" || echo "Clean completed"

      - name: Build signed IPA
        script: |
          cd ios/App
          echo "=== Archiving App ==="
          
          # בניית Archive עם כל ההגדרות הנדרשות
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=462DHLZ9T8 \
            PROVISIONING_PROFILE_SPECIFIER="plaoracodemagic" \
            ENABLE_USER_SCRIPT_SANDBOX=NO \
            SWIFT_VERSION=5.0 \
            CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=NO \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO
          
          echo "=== Archive completed ==="
          ls -la $CM_BUILD_DIR/build/ios/xcarchive/
          
          echo "=== Creating ExportOptions.plist ==="
          cat > /tmp/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>462DHLZ9T8</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>net.planora.app</key>
                  <string>plaoracodemagic</string>
              </dict>
              <key>uploadSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
          echo "=== Exporting IPA ==="
          mkdir -p $CM_BUILD_DIR/build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/ios/xcarchive/App.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ios/ipa \
            -exportOptionsPlist /tmp/ExportOptions.plist
          
          echo "=== IPA files ==="
          find $CM_BUILD_DIR -name "*.ipa" -ls

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive

    publishing:
      email:
        recipients:
          - planora.net@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  ios-unsigned:
    name: iOS Unsigned Build (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        NODE_VERSION: 18
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Set up Node and install dependencies
        script: |
          nvm install $NODE_VERSION || echo "nvm already installed"
          nvm use $NODE_VERSION || echo "using default node"
          npm install --legacy-peer-deps

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor platforms
        script: npm run cap:sync

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build unsigned iOS app
        script: |
          cd ios/App
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $PWD/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Export unsigned IPA
        script: |
          cd ios/App
          mkdir -p Payload UnsignedIPA
          cp -r App.xcarchive/Products/Applications/*.app Payload/
          zip -r App.ipa Payload
          mv App.ipa UnsignedIPA/

    artifacts:
      - ios/App/UnsignedIPA/*.ipa