workflows:
  ios-release:
    name: iOS Release Build (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: Codemagic  # שם ה-API Key שהגדרת ב-Codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store  # או 'development' לבדיקות
        bundle_identifier: net.planora.app
      vars:
        NODE_VERSION: 18
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest

    scripts:
      - name: Set up Node and install dependencies
        script: |
          nvm install $NODE_VERSION || echo "nvm already installed"
          nvm use $NODE_VERSION || echo "using default node"
          npm ci || npm install

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor platforms
        script: npm run cap:sync

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive $CM_BUILD_DIR/App.xcarchive

    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true  # העלאה אוטומטית ל-TestFlight
        # submit_to_app_store: false  # הפעל כשמוכן להעלות לחנות

  # Workflow לבדיקות בסימולטור (ללא חתימה)
  ios-simulator:
    name: iOS Simulator Build (for testing)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        NODE_VERSION: 18
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Set up Node and install dependencies
        script: |
          nvm install $NODE_VERSION || echo "nvm already installed"
          nvm use $NODE_VERSION || echo "using default node"
          npm ci || npm install

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor platforms
        script: npm run cap:sync

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build iOS app for simulator
        script: |
          cd ios/App
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
